### ISSUE TITLE
How to use this library with USB thermal printer

### ISSUE THREAD

**Issue by iamchathu** [TerryTsai/EscPos#1]
How to use this library with USB thermal printer to open cash drawer

**Comment by TerryTsai** [comment]
Sorry Chathu, I do not have any experience with USB receipt printers, so I can't really say. Whenever you do figure out how to send commands though, I have added the DrawerKick command to open the cash drawer. Thanks!

**Comment by iamchathu** [comment]
@TerryTsai Thanks. I will look it and update you on my development

**Comment by monarezio** [comment]
Any success with a USB printer? @TerryTsai
