### ISSUE TITLE
Cut should be send decimal values instead of hexadecimal

### ISSUE THREAD

**Issue by andidev** [TerryTsai/EscPos#2]
The cut(...) method sends hexadecimal values instead of decimal as i spec (65 and 66 decimal in spec).
0x00 and 0x01 do not need to be sent.
should also send `n` at end witch should say number of lines to feed before cutting.

Take a look at 
https://github.com/TerryTsai/EscPos/blob/master/src/main/java/email/com/gmail/ttsai0509/escpos/EscPosBuilder.java#L149-L151

```java
                case FULL:              out.write(0x00); out.write(0x65); break;
                case PART:              out.write(0x01); out.write(0x66); break;
```

should be 

```java
                case FULL:              out.write(65); out.write(0); break; // n which is number of lines to feed is set to 0 here
                case PART:              out.write(66); out.write(0); break; // n which is number of lines to feed is set to 0 here
```

Thanks otherwise for a great builder! Helped me to getting started with my printer.

**Comment by TerryTsai** [comment]
Thanks Anders, you were right... I must have misread the spec. I have since updated it. Appreciate the feedback and glad it has helped in some way.
