### ISSUE TITLE
Second Bill comes broken at the beginning.

### ISSUE THREAD

**Issue by garf** [TerryTsai/EscPos#3]
Hello, 
I'm using your library and it's works awesome. The only thing that I don't know how to solve is second and all following checks prints broken.
![image](https://cloud.githubusercontent.com/assets/1891709/26779278/11ada7ea-49e5-11e7-84a0-912a4a206570.png)
You can check it on this picture. Two same check were printed and on the second one beginning is broken and only `f` symbol printed. But second part of second check print's well. 
Maybe I don't know how to use it?

**Comment by TerryTsai** [comment]
Hi garf,
That does seem strange. Would you mind showing the code you used to generate those tickets? Thank!

**Comment by garf** [comment]
This is the simplifies example of generating data to send to printer:
https://gist.github.com/garf/57b6d463fab19fd8e676657483af987e
If you would like to investigate, here comes the hole app:
https://bitbucket.org/dgaripov/epos-print-server/src/7081a59629ef6e26b348a0bcc42088beb0dfc074/src/main/java/com/garf/epos/converter/DataToEscPos.java?at=master&fileviewer=file-view-default

**Comment by TerryTsai** [comment]
It may have been an issue I recently introduced, but I don't currently have a printer with me to test. I have switched the cut command to its simpler form without the line feed argument. I don't think this version has any problems, but please let me know if you have any more issues.

Edit - I noticed you were using version 1.1 in your project. I am currently using that version in a production environment with no major issues (except for that additional 'f' character). Does performing a FULL cut work?

**Comment by garf** [comment]
Thank you for the answer. I will try it today and will let you know if it's fine. Thank you again!

**Comment by garf** [comment]
Hello. Sorry for the late answer.
I found the problem.
`reset()` and `close()` methods were causing this problem. I just removed tham from my commands sequence and all started to work like charm!
Thank you!
