### ISSUE TITLE
Add Maven Repository

### ISSUE THREAD

**Issue by SimonKlausLudwig** [TerryTsai/EscPos#4]
Add this to your readme:

```
<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
<dependency>
	    <groupId>com.github.TerryTsai</groupId>
	    <artifactId>EscPos</artifactId>
	    <version>0e768dea08</version>
	</dependency>
```
FROM:

https://jitpack.io/#TerryTsai/EscPos/0e768dea08

Its easier for users to use your lib then

**Comment by concernedrat** [comment]
Please add this lib to Maven, or another repository of your choice.

**Comment by TerryTsai** [comment]
Added to maven central, so the jitpack repo is no longer needed. Thanks!
